function isInside = isPointInAxesBounds(x, y, xLimits, yLimits)
% isPointInAxesBounds True when every supplied point is inside the axes.
isInside = ~isempty(x) && ~isempty(y) && ...
    all(isfinite(x)) && all(isfinite(y)) && ...
    all(x >= xLimits(1)) && all(x <= xLimits(2)) && ...
    all(y >= yLimits(1)) && all(y <= yLimits(2));
end
